"""
Django settings for VizHub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

import environ
from decouple import config

 
 

# Add this block inside settings.py
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] 

# Application definition

INSTALLED_APPS = [
    'unfold',
    # "baton", 
    # "jazzmin",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'analytics_hub',  
]

# UNFOLD = {
#     "SITE_TITLE": "VizHub Admin",
#     "SITE_HEADER": "EPHI Admin",
#     "SITE_URL": "/",
#     "SITE_LOGO": {
#         "light": "https://irb.ephi.gov.et/files/site_setting/3a36ebf9b1124f21ee0d704e36272ec9.png",
#         "dark": "https://irb.ephi.gov.et/files/site_setting/3a36ebf9b1124f21ee0d704e36272ec9.png",
#     },
# }
UNFOLD = {
    "SITE_TITLE": "VizHub",
    "SITE_HEADER": "VizHub Analytics",
    "SITE_SUBHEADER": "Data Insights & Visualization",
    "SITE_URL": "/",

    "SITE_ICON": {
        "light": "/static/images/logo.png",
        "dark": "/static/images/logo.png",
    },

    "SITE_LOGO": {
        "light": "https://irb.ephi.gov.et/files/site_setting/3a36ebf9b1124f21ee0d704e36272ec9.png",
        "dark": "https://irb.ephi.gov.et/files/site_setting/3a36ebf9b1124f21ee0d704e36272ec9.png",
    },

    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,

    "ENVIRONMENT": "analytics_hub.admin.environment_callback",

    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
        },
    },
}

BATON = {
    "SITE_HEADER": "VizHub",
    "SITE_TITLE": "VizHub Admin",
    "INDEX_TITLE": "Dashboard",
    "SUPPORT_HREF": "/",
    "COPYRIGHT": "VizHub",
    "POWERED_BY": "Django",
}
BATON = {
    "MENU": (
        {
            "type": "title",
            "label": "Analytics",
        },
        {
            "type": "model",
            "name": "analytics_hub.gbdrecord",
            "label": "GBD Data",
        },
        {
            "type": "model",
            "name": "analytics_hub.visualizationconfig",
            "label": "Visualizations",
        },
    )
}
JAZZMIN_SETTINGS = {
    "site_title": "VizHub",
    "site_header": "VizHub",
    "site_brand": "VizHub",
    "site_logo": None,

    "welcome_sign": "Welcome to VizHub Admin",

    "copyright": "VizHub",

    "navigation_expanded": True,

    "show_sidebar": True,

    "hide_apps": [],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "analytics_hub": "fas fa-chart-line",
    },

    "order_with_respect_to": [
        "analytics_hub",
        "auth",
    ],
}
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",

    "navbar": "navbar-dark navbar-primary",

    "sidebar": "sidebar-dark-primary",

    "accent": "accent-info",

    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_flat_style": False,
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',   
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.locale.LocaleMiddleware',          
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1

# Redirect configuration after login/logout
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Allauth specific settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False

ROOT_URLCONF = "VizHub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "VizHub.wsgi.application"


load_dotenv(BASE_DIR / ".env")

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")

if DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.getenv("DB_NAME", "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }

 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

 


TIME_ZONE = "UTC"

USE_TZ = True

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    # ('am', 'Français'),
 
    ('es', 'Español'),
]

USE_I18N = True
# Note: USE_L10N was deprecated/removed in Django 5.x, you can safely remove it

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
 

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
 
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ANALYSIS_CONFIG = {
    "disease_trends": {
        "filters": ["age_group"],
        "chart": "line",
    },
    "regional_comparison": {
        "filters": ["year"],
        "chart": "bar",
    },
    "gender_disease_distribution": {
        "filters": ["year"],
        "chart": "grouped_bar",
    },
}