# Generated by Django 5.2.6 on 2026-09-08 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GBDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            (
                                "covid_19",
                                "COVID-19 Data Analytics & Modelling Platform",
                            ),
                            ("geospatial_vis", "Geospatial Visualization Platform"),
                            (
                                "childhood_mortality",
                                "Childhood Mortality Indicators Trend Analysis",
                            ),
                            (
                                "child_diarrhea",
                                "Child Health Analysis - Prevalance & Treatment of Diarrhea",
                            ),
                            (
                                "child_fever",
                                "Child Health Analysis - Prevalance & Treatment of Fever",
                            ),
                            (
                                "child_ari",
                                "Child Health Analysis - Prevalance & Treatment of Acute Respiratory Infection",
                            ),
                            (
                                "fertility_trend_nat",
                                "Trends of Fertility Rate for National",
                            ),
                            ("total_fertility_rates", "Total Fertility Rates"),
                            ("general_fertility_rates", "General Fertility Rates"),
                            ("age_specific_fertility", "Age-specific Fertility Rates"),
                            (
                                "vaccination_12_23",
                                "Vaccination Coverage for Age 12 - 23 Months",
                            ),
                            ("anc_visits", "Antenatal Care Visits for Pregenancy"),
                            (
                                "skilled_birth",
                                "Skilled Birth Attendance During Delivery",
                            ),
                            ("first_pnc", "First Postnatal Checkup"),
                            ("delivery_facility", "Delivery in Health Facility"),
                            ("exclusive_breastfeeding", "Exclusive Breastfeeding"),
                            (
                                "early_breastfeeding",
                                "Early Initiation of Breastfeeding",
                            ),
                            ("child_malnutrition", "Levels of Child Malnutrition"),
                            (
                                "perinatal_mortality",
                                "Perinatal Mortality Rate, Number of Still Birth & Early Neonatal Death Analysis",
                            ),
                            (
                                "emonc_assessment",
                                "Emergency Maternal Obstetric Newborn Care Facility Service Assesment Analysis",
                            ),
                            ("climate_health", "Climate and Health Data Visualization"),
                            (
                                "sdg_hstp_tracker",
                                "Health Related SDG & HSTP-II Tracker",
                            ),
                            (
                                "bod_life_expectancy",
                                "Life Expectancy at birth Ethiopia 2019(BOD)",
                            ),
                            (
                                "bod_total_fertility",
                                "Total Fertility Rate in Ethiopia(BOD)",
                            ),
                            (
                                "bod_sdi",
                                "Socio-Demographic Index (SDI) in Ethiopia(BOD)",
                            ),
                            (
                                "bod_maternal_mortality",
                                "Maternal Mortality Rate in Ethiopia(BOD)",
                            ),
                            (
                                "bod_under5_mortality",
                                "Under 5 Mortality Rate in Ethiopia(BOD)",
                            ),
                            (
                                "bod_ncd_premature",
                                "Premature Mortality from NCD in Ethiopia(BOD)",
                            ),
                            (
                                "bod_injury_mortality",
                                "Mortality Rate from All Types of Injuries in Ethiopia(BOD)",
                            ),
                            (
                                "bod_malaria_mortality",
                                "Malaria Mortality Rate in Ethiopia(BOD)",
                            ),
                            (
                                "bod_malaria_incidence",
                                "Malaria Incidence Rate in Ethiopia(BOD)",
                            ),
                            (
                                "bod_cause_premature",
                                "Cause of Premature Mortality in Ehtiopia(BOD)",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("disease", models.CharField(blank=True, max_length=100, null=True)),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                ("facility", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("metric_value", models.FloatField(default=0.0)),
            ],
        ),
    ]
