# Generated by Django 5.2.6 on 2026-09-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("citation", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimensionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FacilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DimensionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "dimension_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics_hub.dimensiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("region", "Region"),
                            ("zone", "Zone"),
                            ("woreda", "Woreda"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analytics_hub.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=100)),
                (
                    "default_chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line"),
                            ("bar", "Bar"),
                            ("pie", "Pie"),
                            ("table", "Table"),
                            ("map", "Map"),
                            ("rank", "Rank"),
                        ],
                        default="line",
                        max_length=20,
                    ),
                ),
                ("supports_confidence_interval", models.BooleanField(default=False)),
                ("supports_map", models.BooleanField(default=False)),
                ("supports_national", models.BooleanField(default=True)),
                ("supports_regional", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="analytics_hub.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualizationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line"),
                            ("bar", "Bar"),
                            ("pie", "Pie"),
                            ("table", "Table"),
                            ("map", "Map"),
                            ("rank", "Rank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("map_enabled", models.BooleanField(default=False)),
                ("national_enabled", models.BooleanField(default=True)),
                ("regional_enabled", models.BooleanField(default=True)),
                ("ranking_enabled", models.BooleanField(default=False)),
                ("color_scheme", models.CharField(blank=True, max_length=100)),
                (
                    "indicator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualization",
                        to="analytics_hub.indicator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geojson", models.JSONField(blank=True, null=True)),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometry",
                        to="analytics_hub.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location"], name="analytics_h_locatio_7b2b74_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("value", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics_hub.cause",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics_hub.datasource",
                    ),
                ),
                (
                    "facility_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics_hub.facilitycategory",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="analytics_hub.indicator",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="analytics_hub.location",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics_hub.sex",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["indicator", "year"],
                        name="analytics_h_indicat_c22405_idx",
                    ),
                    models.Index(
                        fields=["location", "year"],
                        name="analytics_h_locatio_1f03aa_idx",
                    ),
                    models.Index(
                        fields=["indicator", "location", "year"],
                        name="analytics_h_indicat_8b15c0_idx",
                    ),
                    models.Index(
                        fields=["cause"], name="analytics_h_cause_i_afe93f_idx"
                    ),
                    models.Index(fields=["sex"], name="analytics_h_sex_id_cd8c0b_idx"),
                ],
                "unique_together": {
                    (
                        "indicator",
                        "location",
                        "year",
                        "sex",
                        "cause",
                        "facility_category",
                    )
                },
            },
        ),
    ]
