# Generated by Django 5.2.6 on 2026-09-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="analytics_h_indicat_c22405_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="analytics_h_locatio_1f03aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="analytics_h_indicat_8b15c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="analytics_h_cause_i_afe93f_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="analytics_h_sex_id_cd8c0b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="observation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="observation",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics_hub.agegroup",
            ),
        ),
    ]
