# Generated by Django 5.2.6 on 2026-09-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_hub", "0002_agegroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="filters",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="series_dimension",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visualizationconfig",
            name="x_axis",
            field=models.CharField(default="year", max_length=50),
        ),
        migrations.CreateModel(
            name="FilterDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("year", "Year"),
                            ("gender", "Gender"),
                            ("age_group", "Age Group"),
                            ("region", "Region"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics_hub.analysis",
                    ),
                ),
            ],
        ),
    ]
