# Generated by Django 5.2.6 on 2026-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics_hub", "0003_analysis_visualizationconfig_filters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="extra_attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="observation",
            unique_together={
                (
                    "indicator",
                    "location",
                    "year",
                    "date",
                    "sex",
                    "cause",
                    "facility_category",
                    "age_group",
                )
            },
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["indicator", "year"], name="analytics_h_indicat_c22405_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["location", "year"], name="analytics_h_locatio_1f03aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["indicator", "location", "year"],
                name="analytics_h_indicat_8b15c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["date"], name="analytics_h_date_15eabd_idx"),
        ),
    ]
