# Generated by Django 5.2.6 on 2026-09-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics_hub",
            "0004_observation_date_observation_extra_attributes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="age_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics_hub.agegroup",
            ),
        ),
    ]
